version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: workout_db
      POSTGRES_USER: workout_user
      POSTGRES_PASSWORD: workout_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: 