/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { AuthErrorResponseErrorCode } from "./authErrorResponseErrorCode";

/**
 * Authentication error response.
 */
export interface AuthErrorResponse {
  /** Error type */
  error: string;
  /** Internal error code */
  error_code?: AuthErrorResponseErrorCode;
  /** Detailed error description */
  error_description: string;
}
