/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { TokenResponse } from "./tokenResponse";
import type { UserProfileResponse } from "./userProfileResponse";

/**
 * Complete authentication response with user and tokens.
 */
export interface AuthenticationResponse {
  /** JWT token pair */
  tokens: TokenResponse;
  /** User profile information */
  user: UserProfileResponse;
}
