/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { DatabaseHealthResponseDatabase } from "./databaseHealthResponseDatabase";
import type { DatabaseHealthResponseError } from "./databaseHealthResponseError";
import type { DatabaseHealthResponsePoolInfo } from "./databaseHealthResponsePoolInfo";
import type { DatabaseHealthResponseResponseTimeMs } from "./databaseHealthResponseResponseTimeMs";
import type { DatabaseHealthResponseStatus } from "./databaseHealthResponseStatus";

/**
 * Database health check response.
 */
export interface DatabaseHealthResponse {
  database: DatabaseHealthResponseDatabase;
  /** Error message if unhealthy */
  error?: DatabaseHealthResponseError;
  /** Connection pool information */
  pool_info?: DatabaseHealthResponsePoolInfo;
  /** Database response time in milliseconds */
  response_time_ms?: DatabaseHealthResponseResponseTimeMs;
  status: DatabaseHealthResponseStatus;
}
