/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

export type DatabaseHealthResponseDatabase =
  (typeof DatabaseHealthResponseDatabase)[keyof typeof DatabaseHealthResponseDatabase];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatabaseHealthResponseDatabase = {
  connected: "connected",
  disconnected: "disconnected",
} as const;
