/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

export type DatabaseHealthResponseStatus =
  (typeof DatabaseHealthResponseStatus)[keyof typeof DatabaseHealthResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatabaseHealthResponseStatus = {
  healthy: "healthy",
  unhealthy: "unhealthy",
} as const;
