/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { NextAuthTokenResponse } from "./nextAuthTokenResponse";
import type { NextAuthUserResponse } from "./nextAuthUserResponse";

/**
 * Development login response.
 */
export interface DevLoginResponse {
  /** Success message */
  message?: string;
  /** JWT token pair */
  tokens: NextAuthTokenResponse;
  /** User information */
  user: NextAuthUserResponse;
}
