/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

/**
 * Statistics for a single exercise.
 */
export interface ExerciseStats {
  /** Number of times performed */
  count: number;
  /** Exercise unique identifier */
  exercise_id: number;
  /** Exercise name */
  exercise_name: string;
  /** Total number of sets */
  total_sets: number;
  /** Total volume (weight * reps) */
  total_volume: number;
}
