/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseUpdateBodyPart } from "./exerciseUpdateBodyPart";
import type { ExerciseUpdateModality } from "./exerciseUpdateModality";
import type { ExerciseUpdateName } from "./exerciseUpdateName";
import type { ExerciseUpdatePictureUrl } from "./exerciseUpdatePictureUrl";

/**
 * Schema for updating an existing exercise.
 */
export interface ExerciseUpdate {
  /** Primary body part targeted */
  body_part?: ExerciseUpdateBodyPart;
  /** Equipment/modality used */
  modality?: ExerciseUpdateModality;
  /** Exercise name */
  name?: ExerciseUpdateName;
  /** URL to exercise demonstration image */
  picture_url?: ExerciseUpdatePictureUrl;
}
