/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseExecutionUpdateExerciseOrder } from "./exerciseExecutionUpdateExerciseOrder";
import type { ExerciseExecutionUpdateNoteText } from "./exerciseExecutionUpdateNoteText";

/**
 * Schema for updating exercise execution metadata only.
 */
export interface ExerciseExecutionUpdate {
  /** Order of this exercise in the workout (1-based) */
  exercise_order?: ExerciseExecutionUpdateExerciseOrder;
  /** Optional notes about this exercise execution */
  note_text?: ExerciseExecutionUpdateNoteText;
}
