/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseExecutionRequestNoteText } from "./exerciseExecutionRequestNoteText";
import type { SetCreate } from "./setCreate";

/**
 * Schema for creating/updating exercise execution (full replace).
 */
export interface ExerciseExecutionRequest {
  /**
   * Order of this exercise in the workout (1-based)
   * @minimum 1
   */
  exercise_order: number;
  /** Optional notes about this exercise execution */
  note_text?: ExerciseExecutionRequestNoteText;
  /** Sets for this exercise */
  sets?: SetCreate[];
}
