/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseExecutionResponseNoteText } from "./exerciseExecutionResponseNoteText";
import type { SetResponse } from "./setResponse";

/**
 * Schema for exercise execution responses.
 */
export interface ExerciseExecutionResponse {
  created_at: string;
  exercise_id: number;
  exercise_name: string;
  exercise_order: number;
  note_text?: ExerciseExecutionResponseNoteText;
  sets?: SetResponse[];
  updated_at: string;
}
