/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

/**
 * Order of this exercise in the workout (1-based)
 */
export type ExerciseExecutionUpdateExerciseOrder = number | null;
