/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for reordering exercises in a workout.
 */
export interface ExerciseReorderRequest {
  /**
   * List of exercise IDs in desired order
   * @minItems 1
   */
  exercise_ids: number[];
}
