/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseExecutionResponse } from "./exerciseExecutionResponse";

/**
 * Schema for exercise reorder responses.
 */
export interface ExerciseReorderResponse {
  exercise_executions: ExerciseExecutionResponse[];
  message: string;
}
