/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { SimpleHealthResponse } from "./simpleHealthResponse";
import type { DatabaseHealthResponse } from "./databaseHealthResponse";

/**
 * Comprehensive health check response.
 */
export interface FullHealthResponse {
  app: SimpleHealthResponse;
  database: DatabaseHealthResponse;
}
