/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

export type GetUserStatisticsApiV1UsersMeStatsGetParams = {
  /**
   * Start date for statistics calculation (ISO format)
   */
  start_date?: string | null;
  /**
   * End date for statistics calculation (ISO format)
   */
  end_date?: string | null;
};
