/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

export type GoogleOauthCallbackApiV1AuthGoogleCallbackGetParams = {
  /**
   * Authorization code from Google
   */
  code: string;
  /**
   * OAuth state parameter
   */
  state: string;
  /**
   * OAuth error
   */
  error?: string | null;
  /**
   * OAuth error description
   */
  error_description?: string | null;
};
