/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

export type InitiateGoogleOauthApiV1AuthGoogleGetParams = {
  /**
   * Post-auth redirect URL
   */
  redirect_url?: string | null;
};
