/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { NextAuthGoogleUserRequestImage } from "./nextAuthGoogleUserRequestImage";
import type { NextAuthGoogleUserRequestName } from "./nextAuthGoogleUserRequestName";

/**
 * NextAuth.js Google user verification request.
 */
export interface NextAuthGoogleUserRequest {
  /** User's email address from Google */
  email: string;
  /** Whether email is verified by Google */
  email_verified?: boolean;
  /** URL to user's profile image */
  image?: NextAuthGoogleUserRequestImage;
  /** User's display name */
  name?: NextAuthGoogleUserRequestName;
}
