/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

/**
 * JWT tokens in NextAuth.js expected format.
 */
export interface NextAuthTokenResponse {
  /** JWT access token */
  access_token: string;
  /** Access token expiration timestamp in ISO format */
  expires_at: string;
  /** Access token expiration in seconds */
  expires_in: number;
  /** JWT refresh token */
  refresh_token: string;
}
