/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { NextAuthUserResponseImage } from "./nextAuthUserResponseImage";

/**
 * User data in NextAuth.js expected format.
 */
export interface NextAuthUserResponse {
  /** User email address */
  email: string;
  /** User ID */
  id: number;
  /** URL to user's profile image */
  image: NextAuthUserResponseImage;
  /** User display name */
  name: string;
}
