/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response with OAuth authorization URL.
 */
export interface OAuthInitiateResponse {
  /**
   * Google OAuth authorization URL
   * @minLength 1
   * @maxLength 2083
   */
  authorization_url: string;
  /** OAuth state parameter for CSRF protection */
  state: string;
}
