/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { SessionInfoResponseSessionExpiresAt } from "./sessionInfoResponseSessionExpiresAt";
import type { SessionInfoResponseUser } from "./sessionInfoResponseUser";

/**
 * Current session information.
 */
export interface SessionInfoResponse {
  /** Whether user is authenticated */
  authenticated: boolean;
  /** User permissions */
  permissions?: string[];
  /** When the session expires */
  session_expires_at?: SessionInfoResponseSessionExpiresAt;
  /** User profile if authenticated */
  user?: SessionInfoResponseUser;
}
