/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileResponse } from "./userProfileResponse";

/**
 * User profile if authenticated
 */
export type SessionInfoResponseUser = UserProfileResponse | null;
