/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { SetUpdateCleanReps } from "./setUpdateCleanReps";
import type { SetUpdateForcedReps } from "./setUpdateForcedReps";
import type { SetUpdateNoteText } from "./setUpdateNoteText";
import type { SetUpdateWeight } from "./setUpdateWeight";

/**
 * Schema for updating an existing set.
 */
export interface SetUpdate {
  /** Number of clean repetitions completed */
  clean_reps?: SetUpdateCleanReps;
  /** Number of forced repetitions completed */
  forced_reps?: SetUpdateForcedReps;
  /** Optional notes about this set */
  note_text?: SetUpdateNoteText;
  /** Weight used for this set (in pounds) */
  weight?: SetUpdateWeight;
}
