/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { SimpleHealthResponseStatus } from "./simpleHealthResponseStatus";

/**
 * Simple application health response.
 */
export interface SimpleHealthResponse {
  environment: string;
  status: SimpleHealthResponseStatus;
  version: string;
}
