/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { StreakInfoLastWorkoutDate } from "./streakInfoLastWorkoutDate";

/**
 * User workout streak information.
 */
export interface StreakInfo {
  /** Current consecutive workout days */
  current_streak: number;
  /** Date of last workout */
  last_workout_date?: StreakInfoLastWorkoutDate;
  /** Longest consecutive workout streak */
  longest_streak: number;
}
