/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { SystemInfoResponseDatabasePoolConfig } from "./systemInfoResponseDatabasePoolConfig";

/**
 * System configuration information.
 */
export interface SystemInfoResponse {
  api_prefix: string;
  app_name: string;
  database_pool_config: SystemInfoResponseDatabasePoolConfig;
  debug: boolean;
  environment: string;
  log_level: string;
}
