/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */

/**
 * Token refresh request.
 */
export interface TokenRefreshRequest {
  /** Valid refresh token */
  refresh_token: string;
}
