/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { TokenValidationResponseEmail } from "./tokenValidationResponseEmail";
import type { TokenValidationResponseExpiresAt } from "./tokenValidationResponseExpiresAt";
import type { TokenValidationResponseTokenType } from "./tokenValidationResponseTokenType";
import type { TokenValidationResponseUserId } from "./tokenValidationResponseUserId";

/**
 * Token validation response.
 */
export interface TokenValidationResponse {
  /** User email if token is valid */
  email?: TokenValidationResponseEmail;
  /** Token expiration timestamp */
  expires_at?: TokenValidationResponseExpiresAt;
  /** Type of token */
  token_type?: TokenValidationResponseTokenType;
  /** User ID if token is valid */
  user_id?: TokenValidationResponseUserId;
  /** Whether the token is valid */
  valid: boolean;
}
