/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileResponseName } from "./userProfileResponseName";
import type { UserProfileResponseProfileImageUrl } from "./userProfileResponseProfileImageUrl";

/**
 * User profile response.
 */
export interface UserProfileResponse {
  /** User email address */
  email: string;
  /** User ID */
  id: number;
  /** Whether user account is active */
  is_active: boolean;
  /** User display name */
  name?: UserProfileResponseName;
  /** URL to user's profile image */
  profile_image_url?: UserProfileResponseProfileImageUrl;
}
