/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseProfileImageUrl } from "./userResponseProfileImageUrl";

/**
 * User profile response schema.
 */
export interface UserResponse {
  /** When the user account was created */
  created_at: string;
  /** User's email address */
  email_address: string;
  /** User's Google OAuth ID */
  google_id: string;
  /** User's unique identifier */
  id: number;
  /** Whether the user account is active */
  is_active: boolean;
  /** Whether the user has admin privileges */
  is_admin: boolean;
  /** User's display name */
  name: string;
  /** URL to user's profile image */
  profile_image_url?: UserResponseProfileImageUrl;
  /** When the user account was last updated */
  updated_at: string;
}
