/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileUpdateName } from "./userProfileUpdateName";
import type { UserProfileUpdateProfileImageUrl } from "./userProfileUpdateProfileImageUrl";

/**
 * Schema for updating user profile.
 */
export interface UserProfileUpdate {
  /** Updated display name */
  name?: UserProfileUpdateName;
  /** Updated profile image URL */
  profile_image_url?: UserProfileUpdateProfileImageUrl;
}
