/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileResponseProfileImageUrl } from "./userProfileResponseProfileImageUrl";

/**
 * User profile response.
 */
export interface UserProfileResponse {
  /** User email address */
  email_address: string;
  /** Google OAuth user ID */
  google_id: string;
  /** User ID */
  id: number;
  /** Whether the user account is active */
  is_active: boolean;
  /** Whether the user has admin privileges */
  is_admin: boolean;
  /** User display name */
  name: string;
  /** URL to user's profile image */
  profile_image_url: UserProfileResponseProfileImageUrl;
}
