/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { UserStatsResponseBodyPartDistribution } from "./userStatsResponseBodyPartDistribution";
import type { ExerciseStats } from "./exerciseStats";
import type { PersonalRecord } from "./personalRecord";
import type { StreakInfo } from "./streakInfo";
import type { WorkoutFrequency } from "./workoutFrequency";

/**
 * User workout statistics response.
 */
export interface UserStatsResponse {
  /** Distribution of exercises by body part */
  body_part_distribution: UserStatsResponseBodyPartDistribution;
  /** Top exercises by frequency */
  most_performed_exercises: ExerciseStats[];
  /** User's personal records */
  personal_records: PersonalRecord[];
  /** Workout streak information */
  streak_info: StreakInfo;
  /** Total number of exercises performed */
  total_exercises_performed: number;
  /** Total number of sets completed */
  total_sets: number;
  /** Total weight lifted across all workouts */
  total_weight_lifted: number;
  /** Total number of workouts completed */
  total_workouts: number;
  /** Workout frequency statistics */
  workout_frequency: WorkoutFrequency;
}
