/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutResponse } from "./workoutResponse";

/**
 * Workout data if finished, None if deleted
 */
export type WorkoutFinishResponseWorkout = WorkoutResponse | null;
