/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutFrequencyMonthlyCounts } from "./workoutFrequencyMonthlyCounts";

/**
 * Workout frequency statistics.
 */
export interface WorkoutFrequency {
  /** Workout counts by month (YYYY-MM) */
  monthly_counts: WorkoutFrequencyMonthlyCounts;
  /** Average workouts per week */
  weekly_average: number;
}
