/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Workout API
 * A workout tracking API built with FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { WorkoutFinishResponseWorkout } from "./workoutFinishResponseWorkout";

/**
 * Schema for finish workout responses.
 */
export interface WorkoutFinishResponse {
  /** True if empty workout was deleted, False if workout was finished */
  deleted: boolean;
  /** Workout data if finished, None if deleted */
  workout?: WorkoutFinishResponseWorkout;
}
